basePath: /
definitions:
  dto.PatientRegisterPatientRequestDto:
    properties:
      address:
        type: string
      allergies:
        type: string
      birth_date:
        type: string
      blood_type:
        type: string
      emergency_contact:
        type: string
      first_name:
        type: string
      gender:
        enum:
        - male
        - female
        - other
        type: string
      hospital_id:
        description: Patient specific fields
        type: string
      id_card_number:
        type: string
      last_name:
        type: string
      password:
        minLength: 6
        type: string
      phone_number:
        type: string
    required:
    - first_name
    - gender
    - hospital_id
    - last_name
    - password
    type: object
  dto.PatientRegisterResponseDto:
    properties:
      message:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a user API.
  title: User API
  version: "1.0"
paths:
  /patient/register:
    post:
      consumes:
      - application/json
      description: Register a new patient in the system
      parameters:
      - description: Patient registration data
        in: body
        name: patient
        required: true
        schema:
          $ref: '#/definitions/dto.PatientRegisterPatientRequestDto'
      produces:
      - application/json
      responses:
        "201":
          description: Patient registered successfully
          schema:
            $ref: '#/definitions/dto.PatientRegisterResponseDto'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Failed to register user
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Register a new patient
      tags:
      - patients
schemes:
- http
swagger: "2.0"
